feat: add initial infrastructure setup
dose-na-nuvem/infra pull request #1
Opened 2023-11-14 00:41 UTC by luizgribeiro

2023-11-14 17:41 UTC, claudiobastos commented on values.yaml
> +  name: teste-local
Tente dar nomes "completos".

Motivação: facilitar filtrar informação em meio a uma multidão de serviços

Sugestão de partes interessantes:
- projeto: pedagio
- tipo: ms (microservico)
- ambiente: env|qa|prod

Assim fica fácil encontrar coisas como:

pedagio-ms-qa
pedagio-ms-prod

2023-11-14 17:43 UTC, claudiobastos commented on charts/dose-toll-station/templates/deploy.yaml
Seria interessante deixar explícito `config.yaml` injetado.

Devs sempre têm seu tempo desperdiçado tentando encontrar exemplos completamente funcionais dos arquivos e configurações que precisam

😉

2023-11-14 17:45 UTC, claudiobastos commented on Chart.yaml
> +    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
1. não consegui acessar esse link. Está certo ?
2. preferencialmente use a última versão (0.88.0)

2023-11-15 15:35 UTC, luizgribeiro commented on Chart.yaml
> +    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
São coisas diferentes.
1. Esse é o link do repositório que tem os helm charts do open telemetry
2. Vou atualizar a versão, mas a versão do collector não tem relação com a versão do chart (segue o print)

![image](https://github.com/dose-na-nuvem/infra/assets/10711482/9bbd735f-6f82-40bf-94cb-bf88a97bda0b)

2023-11-24 11:42 UTC, EzzioMoreira commented
Uma dúvida, esse chart será utilizado apenas para o MVP? 
Se não, acho que devemos separar o chart da app da stack de monitoramento.

2023-11-24 12:23 UTC, luizgribeiro commented
@ezziomoreira, acho que não tem nada definido com relação a isso.

Acho que seria legal levantar as possibilidades pra explorar e definir como vamos fazer.

Se a gente optar por ter um repo só pros charts poderíamos ter values diferentes com base no ambiente.

2023-11-29 16:23 UTC, claudiobastos requested changes
Entendo que precisa de um README para instruir como configurar e aplicar esse chart

2023-12-02 02:07 UTC, claudiobastos approved these changes
LGTM

2023-12-06 12:18 UTC, merged