feat: adiciona makefile cria cluster k8s
dose-na-nuvem/infra pull request #3
Opened 2023-11-23 11:12 UTC by EzzioMoreira

Adiciona Makefile para provisionar cluster Kubernetes local. 
- Cria cluster
- Implanta ingress-nginx e metrics server

#### Requisitos

- [Docker](https://docs.docker.com/engine/install/)
- [Kind](https://kind.sigs.k8s.io/docs/user/quick-start/#installation)

Para ajuda digite: 

`make help`

Saída do comando:

```shell
help              "Ajuda"
create-cluster    "Cria cluster Kubernetes Kind"
display-cluster   "Exibe cluster Kubernetes Kind"
delete-cluster    "Exclui cluster Kubernetes Kind"
```

2023-11-23 12:22 UTC, claudiobastos requested changes
Há um problema grave e alguns ajustes possíveis

2023-11-23 12:22 UTC, claudiobastos commented on Makefile
> +	docker system prune -f
Exclua ou Revise!
Essa linha remove todas as imagems da máquina onde irá rodar 😨

2023-11-23 12:22 UTC, claudiobastos commented on Makefile
> +    endif
Tem algum problema na linha 48, falha ao tentar criar 😭 

```
$ make create-cluster 
No kind clusters found.
/bin/sh: 2: eval: KIND_CONFIG_FILE_NAME: not found
Creating cluster "k8s-cluster" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼 
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-k8s-cluster"
You can now use your cluster with:

kubectl cluster-info --context kind-k8s-cluster

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
#### Installing ingress-nginx and metrics server####
kubectl apply --filename ...
...
else
make: else: Arquivo ou diretório inexistente
make: *** [Makefile:48: create-cluster] Erro 127

```

2023-11-23 12:22 UTC, claudiobastos commented on Makefile
> +CLUSTER_NAME=k8s-cluster
Que tal um cluster com nome do dose-na-nuvem ? 😄

2023-11-23 13:00 UTC, EzzioMoreira commented on Makefile
> +    endif
Boa, vou ver isso deve ser algo na condição.

2023-11-23 13:04 UTC, EzzioMoreira commented on Makefile
> +	docker system prune -f
Boa, o prume remove os container parados, volume e rede não utilizados. Faz sentido remover esse cara ai pra não gerar impacto nos containers do cliente.

2023-11-24 11:35 UTC, claudiobastos approved these changes
LGTM

2023-11-24 11:36 UTC, merged